country:
  france:
    name: Франция
    costPerUnit: 0.5
    discountEachBillion: 0.99
    currency: EUR
  morocco:
    name: Марокко
    costPerUnit: 5
    multiplierOver: 5
    increasedCost: 6
    currency: AED

spring:
  profiles:
    active: morocco